site_name: "Web3j"
site_description: "Documentation portal for the web3j Blockchain Library"
site_author: "Web3 Labs"
site_url: "https://web3j.io/"

repo_name: "web3j/web3j"
repo_url: "https://github.com/web3j/web3j"

# Copyright
copyright: "Copyright &copy; 2017-2024 Web3 Labs Ltd"


nav:
  - Quickstart: quickstart.md
  - Getting Started:
      - Run a Node locally: getting_started/run_node_locally.md
      - Interacting with a Node: getting_started/interacting_with_node.md
      - Deploy and Interact with Smart Contracts: getting_started/deploy_interact_smart_contracts.md
      - Filters and Flowables: getting_started/pub_sub.md
      - Manual Configuration: getting_started/manual_configuration.md
  - Smart Contracts:
      - Smart Contract Overview: smart_contracts/smart_contracts_overview.md
      - Getting Started with Solidity: smart_contracts/getting_started_solidity.md
      - Compiling Solidity source code: smart_contracts/compiling_solidity.md
      - Construction and Deployment: smart_contracts/construction_and_deployment.md
      - Interacting with Smart Contracts: smart_contracts/interacting_with_smart_contract.md
      - Contract Validity: smart_contracts/contract_validity.md
      - Testing Smart Contracts: smart_contracts/testing_smart_contracts.md
      - Application Binary Interface: smart_contracts/application_binary_interface.md
      - Contracts Supported by Web3j: smart_contracts/contracts_supported_by_web3j.md
  - Transactions:
      - Ethereum Transactions: transactions/transactions.md
      - Obtaining Ether: transactions/obtaining_ether.md
      - Ethereum Test Networks: transactions/ethereum_testnets.md
      - Gas: transactions/gas.md
      - Credentials: transactions/credentials.md
      - Transfer Eth: transactions/transfer_eth.md
      - Transaction Mechanisms: transactions/transaction_mechanisms.md
      - Transaction Nonce: transactions/transaction_nonce.md
      - Transaction Types: transactions/transaction_types.md
      - EIP Transaction Types:
          - EIP-2930 Transaction: transactions/EIP_transaction_types/eip2930_transaction.md
          - EIP-1559 Transaction: transactions/EIP_transaction_types/eip1559_transaction.md
          - EIP-4844 Blob Transaction: transactions/EIP_transaction_types/eip4844_blob_transaction.md
      - Transactions and Smart Contracts: transactions/transactions_and_smart_contracts.md
      - Wallet Files: transactions/wallet_files.md
  - Web3j Eth2 Client: web3j_eth2_client.md
  - Web3j OpenAPI: web3j_openapi.md
  - Web3j Unit: web3j_unit.md
  - Web3j EVM: web3j_evm.md
  - Web3j Sokt: web3j_sokt.md
  - Build Plugins:
      - Solidity Gradle Plugin: plugins/solidity_gradle_plugin.md
      - Web3j Gradle Plugin: plugins/web3j_gradle_plugin.md
      - Web3j Maven Plugin: plugins/web3j_maven_plugin.md
  - Privacy & Permissioning:
      - Besu Quickstart: privacy/besu_quickstart.md
      - Privacy with Hyperledger Besu: privacy/privacy_with_besu.md
      - Privacy Support in Web3j: privacy/privacy_support_web3j.md
  - Advanced:
      - Recursive Length Prefix: advanced/recursive_length_prefix.md
      - Filters and Events: advanced/filters_and_events.md
      - Management Apis: advanced/management_apis.md
      - Ethereum Name Service: advanced/ethereum_name_service.md
      - TLS over HTTP and Websockets: advanced/tls_http_websockets.md
      - HSM Transaction Signing: advanced/HSM_transaction_signing.md
      - Web3j Core Modules: advanced/web3j_core_modules.md
      - Json Web Key (JWK) support: advanced/jwk_support.md
  - Command Line Tools: command_line_tools.md
  - Use Cases:
      - Meta Transactions: use_cases/meta_transaction.md
  - References:
      - Troubleshooting: references/troubleshooting.md
      - Projects using Web3j: references/projects_using_web3j.md
      - Companies using Web3j: references/companies_using_web3j.md
      - Developer Guide: references/developer_guide.md
      - Links and Useful Resources: references/links_and_useful_resources.md
      - Thanks and Credits: references/thanks_and_credits.md
  - Javadoc: https://docs.web3j.io/latest/javadoc-api/
  - Web3j Android:
    - Introduction: android/introduction.md
    - Installation: android/setup_android.md
    - Basic Usage: android/basic_usage.md
    - Testing: android/testing.md

# Configuration
theme:
  name: "material"
  language: "en"
  logo: "img/logo.png"
  favicon: "img/favicon.ico"
  palette:
    primary: "white"
    accent: "deep-orange"


# Customization
extra:
  web3j:
    version: 4.11.0
  android:
    version: 4.6.0
  sokt:
    version: 0.2.1
  version:
    method: mike
  manifest: "manifest.webmanifest"
  social:
    - icon: "fontawesome/brands/github-alt"
      link: "https://github.com/web3j"
    - icon: "fontawesome/brands/twitter"
      link: "https://twitter.com/web3labs"
    - icon: "fontawesome/brands/linkedin"
      link: "https://linkedin.com/in/web3labs"



extra_css:
  - "stylesheets/extra.css"
  - "css/version-select.css"


  # Google Analytics
  - css/version-select.css
google_analytics:
  - 'UA-85710619-1'
  - 'auto'


# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - pymdownx.details
  - toc:
      permalink: true
      toc_depth: 3
extra_javascript:
  - js/version-select.js

plugins:
  - search
  - markdownextradata: {}
